### ISSUE TITLE
Questions about the new foam sim

### ISSUE THREAD

**Issue by Midda-C** [huwb/crest-oceanrender#33]
So we've got things up and running in our project now.  to get started, I began getting the foam back on the ocean surface, but I have a few questions.

1. Could you clarify what exactly the Strength and Coverage settings do?  I can see changes when I adjust them, but I'm not entirely sure what their differences are.

1. What is the intention with the additional Coverage parameter on the material (also, I think it's inverted now?  It seems to remove foam the higher you set it, I think it used to be the other way around)

1. Am I correct to assume that, like the wave shapes, it's okay to run several foam sims with different settings as long as they're not doubling-up on the same wavelengths?

1. I may be mistaken, but was there previously an overall fade/alpha parameter for the foam on the ocean material?  I don't know if I'm imagining that or not, but either way, that would be helpful.

1. With the old foam, we were able to get some nice stylised (i.e. not realistic, but appropriate for our art-style) foam on the peaks of the higher-frequency waves.  I'm having a hard time replicating this with the foam sim, could you give some guidance on how something similar might be achieved?  [Here's an example](https://user-images.githubusercontent.com/37893722/43499941-5970a7fa-9591-11e8-9293-845885bd65e6.png) of how we had it configured on the previous release.

Thanks!

**Comment by huwb** [comment]
Thanks these are great questions and its revealing to see what is confusing to a fresh pair of eyes - very helpful!

Few words about the system - the details of which leak into the parameter names/meanings unfortunately and will be required to speak to your questions..

Simulation: The new system has a persistent foam buffer. Each frame foam is added into this buffer from different sources (from gerstner waves, from shallow water/coastlines, from dynamic wave sims, ..). These all add foam each frame, and then the foam is also multiplied by a factor < 1 to reduce it over time to model foam dissipating. The values in the foam buffer have no meaning and can be any number greater than 0.

Render: The ocean material reads the foam value from the buffer. It then decides how much foam to draw by thresholding the value from the foam buffer. This thresholded value then drives a black point fade.

Its not ideal that there are so many transformations of this value. In particular there are tweakable variables in both the foam generation and foam rendering which are not independent. Maybe i should try to remove the thresholding step - attempt to use the foam value straight from the buffer to drive the render. I will experiment and let you know.


1. Assume these are on the sim settings. These have tooltips but maybe not useful (?), i'll look at updating them. They both control how foam is generated from gerstner waves. Strength is an intensity multiplier - which is fairly abstract. I guess its a balancing mechanism that is a potential for removal. Coverage is how much of the wave generates foam - can be used to focus foam generation on peaks.
2. Coverage on the material is the thresholding step mentioned above - converts from an unbounded foam value to a black faded foam. I vaguely remember it got inverted and I couldn't easily uninvert it due to the change in calculation, but I'll take another look.
3. Yes, picking a range of wavelengths/resolutions is a good thing, and doubling up would repeat computation and add double the amount of foam for that resolution which is bad. I might guard against or warn in the case of repeated resolutions actually as this should never be necessary.
4. Yeah, it sneakily uses the alpha channel of the foam colour to fade the foam!
5. Hmm.. wave amplitude and chop will help here. The parameters for foam gen above may help, but they would affect all wavelengths. If you dont find the degrees of freedom you're looking for, i could add a per-resolution strength override, i think this can be plugged in simply with minimal overhead.

**Comment by Midda-C** [comment]
Whoops, didn't even notice the tooltips.  Yeah, I think they're sufficiently clear, I just completely missed them!

D'oh, didn't even think to adjust the alpha on the foam colour.  Makes sense.  However, I'm adjusting it now, and it doesn't seem to be having an effect.  Is it broken, or am I missing something?

Hmmm, yeah maybe the strength override might be helpful.  I can't really get anything like the old small foam caps we had, so if you think that'd help, I'm keen to try.

**Comment by huwb** [comment]
> Is it broken, or am I missing something?

Of course it's broken :).. apologies.. fixed with the referenced commit on master now.

Ok noted, I am fire fighting a few other things but will leave this open for later.

**Comment by Midda-C** [comment]
Hah, thanks, alpha is working as expected now. :)

**Comment by holdingjason** [comment]
BTW when you say wave amplitude are you talking about the spectra values?  Otherwise I am not sure where wave amp is.  Right now the spectra size has to hit a threshold (fairly large) in order for foam to show up.  Thanks

>>>Hmm.. wave amplitude and chop will help here. The parameters for foam gen above may help, but they would affect all wavelengths. If you dont find the degrees of freedom you're looking for, i could add a per-resolution strength override, i think this can be plugged in simply with minimal overhead.

**Comment by Midda-C** [comment]
Hi @holdingjason!  No, I haven't managed to match the pre-2.0 foam in that respect.

Let me preface the following by saying that I really love the new foam sim, and it's definitely an improvement.  Seeing the foam fade and accumulate in a believable way is great!

But—and maybe this is because our project is quite stylised, so our needs might be a bit off-target with regards to Crest's overall goals—but I feel that a combination of the new foam sim for the larger LODs and the old shader-based faux-foam (fauxm?!) for the finer LODs would best-suit our needs.

Of course, my brain just falls back to that because it's what I already know, and I totally understand if @huwb is reluctant to resurrect old solutions.  If the same result could be achieved with the new foam sim, great, I just don't want to request potentially finicky work if its use-case is very narrow.

**Comment by holdingjason** [comment]
Hi @Midda-C.   Agree with what you said.  Just not sure I totally understand how the foam works at this point so need to bang on it some more.  The effects are just odd that I am getting so far, so if you look at that second video that foam just does not seem correct.  As it drags and creates these circular patterns which does not look great.  

https://drive.google.com/open?id=1QarT6ULbAFMin18UZtCU-mLm9kHfVpG3

However maybe this is something I am messing up so need to take another look at the demo project and play around more.  I do love how the foam fade and accumulation work on more static scenes ie less driving waves so must be something I am doing wrong.

**Comment by huwb** [comment]
Hi guys,

Apologies its taken me a while to respond. I'll do my best to break this thread into individual points and respond to each one. I'll write my interpretation of each one - please let me know if i've misunderstood or if I've missed something. I'm going to write generic-ish stuff at first but can get more specific as I understand the issues better. Perhaps we can use the numbers below to help structure the discussion going forwards.

1. Not getting small foam caps anymore - is this because foam fades gradually over time (so generally covers larger areas)? One way to solve this might be to ramp up the Foam Fade Rate to make it fade quicker? On the other hand if the issue is that its not picking up small waves, adding a finer resolution sim might help (add smaller resolution to CreateSims Simulation Layers.
2. Blue green shades from troughs to peaks - I want to revisit the wave colouring. I dont think the bubbles are the right way to get different colours on troughs vs peaks - the bubbles are infused into the water in turbulent areas and should be left behind the waves. As a next step i was considering limiting bubbles to be strictly after the waves (but i need to watch more reference). So the bubbles would not contribute much to the colour of an oncoming (front side) of a wave. Continue reading to the next point..
3. I think the primary source of colour differentiation between troughs and peaks should be simulating more light transport through the wave. This should not depend on bubbles - I imagine we want this colour variation even when there are no bubbles/foam. I think the look was leaning heavily on the foam previously, but should work without any foam at all. The recent versions of the ocean lack this nice variation in colour, except when looking towards the sun. I want to bring back some of the subsurface scattered light. I think ocean implementations usually add light based on the height of the surface. I can get some okish results adding a term in the subsurface computation based on height, but it has limitations. Should i look at getting something like this pushed to a branch for experimentation?
![image](https://user-images.githubusercontent.com/939901/44075146-5fa73d42-9fbd-11e8-87f5-74dab56466b0.png)
4. Foam range (how far visible in the distance) - this can be increased by adding more foam sim resolutions. (I am thinking of refactoring the simulation setup so that you directly specify what range you want foam at, and it generates the necessary sims automatically). It should be possible to get foam at the same distance in v2 as in v1, but it might depend on the foam generation params. As a test you could make sure all the foam sims are there up to 32m resolution, and then ramp up the wave foam strength and wave foam coverage. That might look funky in the foreground but would confirm the foam range.
5. Foam range part 2 - looking at your last video @holdingjason , your ocean seems to have mostly small wavelengths - these waves will not be drawn very far into the distance, which is probably why you don't see a great range. This should be common to both v1 and v2 and is how the ocean system is so efficient - detailed/small/sharp things are only computed in the mid to foreground. There are two settings that allow this behaviour to be tweaked. If you have frame budget, you can increase the amount of detail in the ocean, which should mean there is enough verts to render those waves further into the distance. Try doubling the Base Vert Density on the OceanRenderer script. The other option is you might decide that I'm being too conservative with the limits for the verts required to render a wave - you could reduce the Min Texels Per Wave - right now it wants at least 5 verts to tessellate a wave shape, but you could reduce to 4 or 3. You may see some sharp corners/edges, but this should then draw your waves further back into the distance. I think i chose pretty conservative values and I didnt have a real production scenario to trade these off.
6. Round foam patches - i see what you mean. I think this is a result of the regularity of your waves. I dont know if it matches the style your going for but you could add some more small waves by ramping up the small wavelengths in the spectrum? This should break up the repeating patterns somewhat. If you don't want foam to be left behind you could use high foam fade rate.
7. Resurrecting old solution - i strongly recommend talking the above points through and pushing on the new system (i can add features if need be) because the new should be able to achieve what the old did, or better. Also if you set the foam fade rate to a high value, it becomes almost equivalent to what was there before (and actually with a minor code refactor i think i could make the foam generation part exactly equivalent to what was there before - i will think about doing this). However @holdingjason it sounds like your in a bit of a bind so while I don't currently feel stoked about having two foam systems integrated into crest at once, it would be possible to bring back the V1 foam - the inputs should all still be there (i think), so it would be a case of bring back the old code - compute the determinants of the displacement texture in the SampleDisplacements functions, and then you could bring back the old fragment shader code. I'm willing to help with this (i could make a branch off V2), but I'm not able to give you a guarantee as to when - I'm off for the next two weeks. This would also probably close the door to future foam improvements which I hope to make, and would rather everyone came along for the ride, but the option is there.
8. @Midda-C interesting idea about mixing old and new. I think my preference for achieving this would be to break out the foam generation params on a per-lod basis as mentioned above, and then you could set the foam fade rate to be high in the background so the foam is generated but does not sit on the water over time. However i wouldnt vote to go here immediately, but would like to confirm the above and do any fixes to whats there currently first.

**Comment by Midda-C** [comment]
Hey!

1.  Yeah, I've cranked the fade speed right up, which does actually get it pretty close.  However, it also seems that the foam generated from the wake in the dynamic wave sim ends up fading really quickly too, which looks a bit odd.  I assume that's because they're being generated on the same resolutions?

1.  Agreed, some more variation from peaks to troughs would be nice.  With our settings of having the foam concentrated on the peaks, the bubbles aren't really enough to get a nice falloff.

1.  Yeah, I'm finding that our sunset/sunrise are the times of day where the ocean looks struly stunning, and I put that down to the scattering.  During, say, midday, it still looks nice, but more colour variation in the peaks and troughs would be great.  Sea of Thieves does a great job of getting that nice subsurface light even when the light is prety much straight overhead.  I have no idea if that's accurate, but it looks beautiful.

1. Had this issue too, but I just extended out the foam sims out to 32m (just picked every second resolution rather than all of them), and that seems to have worked pretty well.

1. Ooohhh, that's what the Texels Per Wave is doing!  I wasn't sure exactly what it meant under the hood.  That makes sense.  Yeah, I just reduced this to 3 and I'm getting nicer results.

1. I see these round shapes in our foam a bit, too.  Maybe some random noise (or a texture?) could be used on top of just the 'age' of the foam to fade it out?  Sort of like on particle systems how you can set the age of a particle to be random between a couple values.  That might help combat the uniform shape?

1. After reading through everything here and taking the time to play with things, I'm getting nicer results.  I know I brought up the old sytem, but I personally don't think that's needed now.  The foam sims are a much more versatile solution.

1. Again, yeah, I don't think a mix is necessary.  With your explanations/clarifications here, I'm able to get an overall better foam solution than we had before.  It's not the same, but that doesn't matter, it's not like it was perfect before.  I'm keen to see how it'll look with some of the improvements you've mentioned.

It's worth mentioning that, in my playing around with it just now, I did end up going in and modifying a few material properties by hand, as the ranges were a bit too restrictive.  One was the foam normal strength.  With our texture, along with having the feather value turned up, the foam normals were barely visible.  I edited the material file to be much higher (around 50), however, this may just be something with our texture.  If you're reluctant to extend ranges too much, that's fine, I'm happy to just edit the material to suit our needs.  I'd already done this a while back with the direction light falloff and boost.

But what the hell are you doing reading/worring about this on your holiday, anyway?  Go relax and have a glass of scotch!

**Comment by huwb** [comment]
:) its very chill holiday with lots of spare time so I'm dipping in and out when i feel like it!

@holdingjason i 'unhashed' the numbers in your post, hope you dont mind - it picked them up as crossreferences to other crest issues!

> and actually with a minor code refactor i think i could make the foam generation part exactly equivalent to what was there before

I've done this now in ef46f42a8c564e85f06c874da71f68a1dd335639 - if you crank up the foam fade rate, it will remove any foam from the last frame, so you get back to the old system where the foam is instantaneous rather than persistent.

ill respond to the rest in a bit!

**Comment by holdingjason** [comment]
Thanks a ton changes all look great.  Agree with @Midda-C on his points after grabbing the latest.  Very powerful changes.  Still need time to play with everything there is so much to go through now 👍 however my initial playing around it seems like I am able to get some really nice results.

Still need to play around with putting in longer or shorter "gaps" between wave types.  I was able to speed up or slow down the waves using gravity so that worked like a charm.

**Comment by Midda-C** [comment]
The new changes with the high fade-rate make it so I'm able to replicate the old foam peaks pretty much exactly.  Yay!

I am getting some weird jitter on the foam though when I'm move the camera.  It only seems to be happening when the fade rate is set really high.  It's fine when the camera is still, but it's pretty distracting during movement.

Here's a short clip:
https://drive.google.com/open?id=1n2xeDM46q01AKOgeeMLDscqfteg2KKWH

Is that happening for anyone else?

**Comment by holdingjason** [comment]
I will try and replicate on my side.  Do you have some easy settings to pass on to replicate it?

I will try in the mean time.

**Comment by huwb** [comment]
@Midda-C regarding the jitter, are you able to get a similar shot with time frozen?

**Comment by Midda-C** [comment]
Sure.  It looks perfect when timescale is set to zero.  The lower the timescale, the less it jitters.  I can't even notice it at all with the timescale set to 0.1x

Here's a clip with the time frozen, then at half speed, then at full speed.  It's less apparent at 50%, but it's there.  Please excuse the crappy framerate.

https://drive.google.com/open?id=1p6HldO_m0ZlsPwAi-7nCtzPkUV0G8Rg_

**Comment by holdingjason** [comment]
BTW looks like your already covered @Midda-C  but I can replicate on my side as well.  Not a pronounced as you but I can see it, again only at very very high fade rate.

**Comment by huwb** [comment]
Hi guys

1. @Midda-C  yes the foam is generated in a unified way for all types of water waves, and faded globally. interestingly, it would be possible to run 3 different foam sims, say for gerstner waves, dynamic waves (wake), and shorelines (cf #40), by adding multiple channels to the foam texture. any thoughts?
2. Wave colours - i still plan to improve the wave colouring, but during my refactor i cranked up bubbles in the main example scene which adds some of this interest back in, FYI.
4. There was a fairly savage bug related to foam thats fixed in the refactor merge as well (same PR - #48). it was erroneously accumulating foam down the lod chain from the biggest lod down to the detailed lod. it meant the foam strength near the viewer was many times stronger than in the distance. now that this is fixed i can see foam in the distance which is pretty cool. Sorry for this bug, its quite a nasty one.
9. Jitter (just added) - i rebuilt a lot of stuff in the Big Refactor and it should be more robust. Running on latest now I dont see any of that flicker, even when i introduce random framerate using the Sleeper script (example content). If/when you get a chance could i get a retest on latest please? There might be some fixup required due to a lot changing in the refactor, i've summarised what i think is required in #48 .

Slider ranges - @Midda-C yes i am interested - could you let me know which ranges you've changed? i'm in favour of taking them unless they seem really extreme (and then ill be curious to discuss why!).

**Comment by Midda-C** [comment]
Hey!  We grabbed what was in the refactor branch today and dropped it into our project to check it out.  After updating the necessary layer names and such, it mostly just worked, though @dizzy2003 is having some issues with updating one of our scripts for the dynamic wave sim.  He went to look at the included assets, but ehe Crest-Examples scenes (like threeboats) have a bunch of missing prefabs for some reason, even though the prefabs appear to exist.  Seems like Unity is doing something strange.

Really like the changes though.  I managed to tweak the foam with far less fiddling around  Really cool!  The jitter seems to have been resolved too!

1—Having the option to tweak the shoreline foam independently would probably be good.  At the moment, we don't really have much shoreline foam to speak of, since it's sharing the rapid fade speed of the gerstern waves.  Maybe the wake too.  We need to get our dynamics working correctly again before I can be sure about that, though.  That might be okay as is (though of course other projects may have other needs).

2—Yup, I turned it up today on our material, too.  It definitely helps.

4—The foam definitely seems to draw in and out over disntaces in a less jarring manner.  With our settings, we're not really seeing any foam if it's view from a fairly high altitude (like from atop a tall cliff), but again, it fads in a more appealing way now.  I sort of feel like we'd want to have a near and far foam setting.  We could maybe just lerp the foam sim values based on how car we are from the ocean surface.

9—As mentioned above, the jitter seems to be completely gone now.  Hooray!

Regarding slider ranges—The first ones I modified were the directional-light fall-off and boost, which we now have set to 4096 and 512 respectively.  I know—that's a huge difference!  It seemed to be the easiest way to get that nice sparkle going (like [this in Sea of Thieves](https://image.noelshack.com/fichiers/2017/16/1492899646-sot-1.png)).  I'd like to get a much wider spread like you can often see in real life, but I think that might come down to our normal map.

I think the only other one I've got modified at the moment is the normal strength, which is currently at 30.  This was because we've got the feather turned up to 1, so cranking up the normal strength gave back the nice shading to the shoreline.  However, it's not really doing much at the moment, since we don't have much shoreline foam presently.  I wouldn't have the normal strength up that high if I had the feather turned down to something lower.  If we can set the shorline foam independently of the rest of the foam sim, this will likely be turned back down.

To be clear though, our current settings are by no means final.  I expect them to be prodded and poked for some time while we settle on a look we like.  Then we also need to tweak it for different ocean conditions.

**Comment by huwb** [comment]
The prefab issue is worrying. Sometimes deleting the Library folder helps to unconfuse unity. However if its a legit problem please me know.

I pushed the slider ranges, thanks!

**Comment by holdingjason** [comment]
Just pulled latest and working with it.  So far so good.  Just a minor weird issue I see is that the crest logo disappears/flickers when I move towards it.  Again not sure if this is a real issue or not but figured I would mention it.

#4 I can now see foam at a distance as you mentioned so that looks fixed.

Jitter for foam looked fixed.  But again I mention that crest logo.

Will let you know about shore foam vs ocean foam.

**Comment by holdingjason** [comment]
So sims are gone now it appears which I was using to "fix" the shore vs ocean foam issue.  Had two different ones running one for shore one for the ocean.  So yes will need #1 from your list which @Midda-C  talked about and agree with his points on it.  We have a lot of shoreline that we need to control, mostly because we want a light foam so it does not obscure things like fish etc near the shore.

**Comment by Midda-C** [comment]
> The prefab issue is worrying. Sometimes deleting the Library folder helps to unconfuse unity. However if its a legit problem please me know.

I actually did a full reimport of our project today—not willingly, my PC bluescreened while getting latest from Perforce today, and it broke Unity reeeeaaal good >:( —and the prefab issue persisted.  I also tried just dumping the crest folders into a completely new project, and the scenes still claim they're missing.

**Comment by huwb** [comment]
I again unhashed (removed the #) from some of the numbers above so that it doesnt create random links to irrelevant issues.

I've broken out what i believe are the two major follow ups into two new issues:

#51 - broken prefabs
#52 - improve light scattering options through waves
#53 - flickering alpha on surface (crest logo)

Could we please move relevant discussions there.

Is there anything I'm missing? If not then i'll close this out.

Thanks!

**Comment by Midda-C** [comment]
All good here, feel free to close this one. :)
