### ISSUE TITLE
Render Ocean Depth component not working with Terrain objects

### ISSUE THREAD

**Issue by Midda-C** [huwb/crest-oceanrender#8]
Hi, I grabbed the latest data to evaluate, and tried to get it working inside our existing project.  Most things were working as expected, but when I added the Render Ocean Depth component to our terrain (which is a Unity Terrain object, rather than a regular mesh), I get the following errors spammed in the log:

`ArgumentNullException: Argument cannot be null.
Parameter name: renderer
UnityEngine.Rendering.CommandBuffer.DrawRenderer (UnityEngine.Renderer renderer, UnityEngine.Material material, Int32 submeshIndex, Int32 shaderPass) (at C:/buildslave/unity/build/artifacts/generated/common/runtime/RenderingCommandBufferBindings.gen.cs:362)
UnityEngine.Rendering.CommandBuffer.DrawRenderer (UnityEngine.Renderer renderer, UnityEngine.Material material) (at C:/buildslave/unity/build/artifacts/generated/common/runtime/RenderingCommandBufferBindings.gen.cs:356)
Crest.WaveDataCam.UpdateCmdBufOceanFloorDepth () (at Assets/Crest/Scripts/WaveDataCam.cs:168)
Crest.WaveDataCam.Update () (at Assets/Crest/Scripts/WaveDataCam.cs:62)
`

I tried just creating a regular cube mesh, and the component worked on that fine, so I suspect it's something specific with Unity Terrains?

**Comment by huwb** [comment]
Ha, I had not thought of trying a Terrain. Yes it doesnt look like Unity Terrain uses a Renderer component (unlike all the other things..). It must use internal paths to render. Terrains seem to be incompatible with command buffer rendering (also asked here https://www.reddit.com/r/Unity3D/comments/6k5pcq/is_there_any_way_to_render_terrain_in/ but not reply).

Luckily on the weekend i implemented a more efficient path which renders the depth once on startup instead of rendering every frame, and this does not rely on command buffers and it appears to work, as per this beautiful work of art i just made:

![image](https://user-images.githubusercontent.com/939901/39779463-245a0638-5301-11e8-9a70-a04e4ae40535.png)

To use it, see the IslandDepthCache GO with the Ocean Depth Cache component. You use the gizmo to place, orient and scale the cache, and set the Mask to select what objects to render into it. You can dupe the existing cache or create new ones and it should Just Work (tm). Let me know if you get a chance to try it.

I resolved this by making a clear error message when you attempt to tag up a Terrain, and added some docs.

**Comment by razzraziel** [comment]
Unity Terrain still doesnt get rendered with this render cam technique. It just renders meshes but not terrains. 

I tried this with latest repo.

https://i.ibb.co/7gL2HPc/image.png

**Comment by razzraziel** [comment]
Oh ok, it is already known issue for instanced terrains (Draw Instanced @ Unity 2018.3)

Here is the workaround:
https://github.com/huwb/crest-oceanrender/commit/4af17b0418a2450ef89f9b0b77a384a0d5ddb22c
